# Generated by Django 4.2.7 on 2024-04-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': False, 'verbose_name_plural': 'Employees'},
        ),
    ]
