# Generated by Django 4.2.7 on 2024-04-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApi', '0002_alter_employees_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobhistory',
            options={},
        ),
    ]
