# Generated by Django 4.2.7 on 2024-04-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApi', '0003_alter_jobhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobhistory',
            options={'managed': False},
        ),
    ]
